version: "3.9"
services:
  database:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employees
      - POSTGRES_PASSWORD=testing
    # volumes:
    #   - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
    - "8080:8080"
# volumes:
#   data: