apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wibi-server
  name: wibi-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wibi-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wibi-server
    spec:
      containers:
      - image: 010573/practice-deployment:latest
        env:
        - name: host
          value: db.default
        - name: port
          value: "5432"
        - name: user
          value: postgres
        - name: dbname
          value: employees
        - name: password
          value: testing
        name: nginx
        resources: {}
        ports:
        - containerPort: 8080
      - image: nginx:alpine #sidecar
        name: nginx2
        ports:
        - containerPort: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: wibi-server
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8080
  selector:
    app: wibi-server
---
apiVersion: v1
kind: Service
metadata:
  name: wibi-server-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: wibi-server

# kubectl create deploy server --image nginx:alpine --dry-run=client -o yaml